### ISSUE TITLE
Make Site Responsive

### ISSUE THREAD

**Issue by carlihudson** [carlihudson/challengethree-carli-hudson#3]
# Make Site Responsive

## User Story
As a user, I want a website that is formatted well no matter what device I'm reading it on

## Acceptance Criteria
It is done when there are added media queries and other CSS rules to make the application responsive on any and all devices.

**Comment by abitsalihu** [comment]
Hey @carlihudson, I would like to help with this issue. :)

**Comment by carlihudson** [comment]
Hi @abitsalihu ! Thank you for your offer! This is actually a project for school so I have to do it myself. (And actually I think it was already done anyway)
